#!/bin/bash
# Ralph Wiggum Toolkit - Recipe-aware init
# Creates the file structure needed for spec-driven development loops

set -euo pipefail

PLUGIN_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
RECIPES_DIR="$PLUGIN_ROOT/recipes"

# Track what was created vs skipped
CREATED=()
SKIPPED=()

create_if_missing() {
  local target="$1"
  local source="$2"
  local description="$3"

  if [[ -f "$target" ]]; then
    SKIPPED+=("$description ($target already exists)")
  else
    cp "$source" "$target"
    CREATED+=("$description → $target")
  fi
}

create_dir_if_missing() {
  local target="$1"
  local description="$2"

  if [[ -d "$target" ]]; then
    SKIPPED+=("$description ($target already exists)")
  else
    mkdir -p "$target"
    CREATED+=("$description → $target")
  fi
}

# Escape sed replacement metacharacters for delimiter '|'
escape_sed_replacement() {
  printf '%s' "$1" | sed -e 's/[&|\\]/\\&/g'
}

# Escape a string for safe embedding in JSON values inside a heredoc
escape_json_value() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/\$/\\$/g' -e 's/`/\\`/g'
}

# ============================================================
# SHARED INIT (common to all recipes)
# ============================================================
init_common() {
  create_dir_if_missing "specs" "Specs directory"
  create_dir_if_missing "ralph" "Ralph state directory"

  # Create empty IMPLEMENTATION_PLAN.md
  if [[ ! -f "IMPLEMENTATION_PLAN.md" ]]; then
    echo "<!-- Generated by Ralph Wiggum Toolkit - will be populated during planning phase -->" > IMPLEMENTATION_PLAN.md
    CREATED+=("IMPLEMENTATION_PLAN.md")
  else
    SKIPPED+=("IMPLEMENTATION_PLAN.md (already exists)")
  fi

  # Copy loop.sh from core
  if [[ ! -f "loop.sh" ]]; then
    cp "$PLUGIN_ROOT/core/scripts/loop.sh" "loop.sh"
    chmod +x "loop.sh"
    CREATED+=("loop.sh (executable)")
  else
    SKIPPED+=("loop.sh (already exists)")
  fi
}

# ============================================================
# REPORT RESULTS
# ============================================================
report_results() {
  echo ""
  if [[ ${#CREATED[@]} -gt 0 ]]; then
    echo "Created:"
    for item in "${CREATED[@]}"; do
      echo "  + $item"
    done
  fi

  if [[ ${#SKIPPED[@]} -gt 0 ]]; then
    echo ""
    echo "Skipped (already exist):"
    for item in "${SKIPPED[@]}"; do
      echo "  - $item"
    done
  fi
}

# ============================================================
# GREENFIELD INIT
# ============================================================
init_greenfield() {
  # Parse greenfield-specific args
  local SRC_DIR="src"
  local GOAL=""

  set -- "${REMAINING_ARGS[@]}"
  while [[ $# -gt 0 ]]; do
    case $1 in
      --src-dir)
        if [[ -z "${2:-}" ]] || [[ "${2:-}" == -* ]]; then
          echo "Error: --src-dir requires a path argument" >&2
          exit 1
        fi
        SRC_DIR="$2"
        shift 2
        ;;
      --goal)
        if [[ -z "${2:-}" ]] || [[ "${2:-}" == -* ]]; then
          echo "Error: --goal requires a text argument" >&2
          exit 1
        fi
        GOAL="$2"
        shift 2
        ;;
      -h|--help)
        cat << 'EOF'
Ralph Wiggum Toolkit - Greenfield Init

USAGE:
  /ralph init [--recipe greenfield] [OPTIONS]

OPTIONS:
  --src-dir <path>   Source code directory (default: src)
  --goal <text>      Project goal for PROMPT_plan.md placeholder
  -h, --help         Show this help

CREATES:
  ralph/manifest.json     Project manifest
  specs/                  Requirement specs directory
  AGENTS.md               Operational guide (build/test commands)
  IMPLEMENTATION_PLAN.md  Task tracking (initially empty)
  PROMPT_plan.md          Planning mode prompt
  PROMPT_build.md         Build mode prompt
  loop.sh                 External autonomous loop runner
EOF
        exit 0
        ;;
      *)
        echo "Warning: Unknown argument '$1' ignored" >&2
        shift
        ;;
    esac
  done

  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "Ralph Wiggum Toolkit: Initializing (greenfield)"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  # Shared setup
  init_common

  # Create files from templates
  create_if_missing "AGENTS.md" "$TEMPLATES/AGENTS.md" "AGENTS.md"
  create_if_missing "PROMPT_plan.md" "$TEMPLATES/PROMPT_plan.md" "PROMPT_plan.md"
  create_if_missing "PROMPT_build.md" "$TEMPLATES/PROMPT_build.md" "PROMPT_build.md"

  # Create greenfield manifest
  if [[ ! -f "ralph/manifest.json" ]]; then
    local SAFE_SRC_DIR
    SAFE_SRC_DIR="$(escape_json_value "$SRC_DIR")"
    local SAFE_GOAL
    SAFE_GOAL="$(escape_json_value "${GOAL:-[project-specific goal]}")"
    cat > ralph/manifest.json <<MANIFEST_EOF
{
  "version": "3.0.0",
  "recipe": "greenfield",
  "src_dir": "$SAFE_SRC_DIR",
  "goal": "$SAFE_GOAL",
  "default_model": "opus",
  "created": "$(date +%Y-%m-%d)",
  "phases": {
    "plan": { "status": "pending" },
    "build": { "status": "pending" }
  }
}
MANIFEST_EOF
    CREATED+=("ralph/manifest.json")
  else
    SKIPPED+=("ralph/manifest.json (already exists)")
  fi

  # If source dir is not "src", update prompt templates to use the right path
  if [[ "$SRC_DIR" != "src" ]]; then
    ESCAPED_SRC_DIR="$(escape_sed_replacement "$SRC_DIR")"
    for f in PROMPT_plan.md PROMPT_build.md; do
      if [[ -f "$f" ]]; then
        sed -i '' "s|src/lib/\*|${ESCAPED_SRC_DIR}/lib/*|g; s|src/\*|${ESCAPED_SRC_DIR}/*|g" "$f" 2>/dev/null || \
        sed -i "s|src/lib/\*|${ESCAPED_SRC_DIR}/lib/*|g; s|src/\*|${ESCAPED_SRC_DIR}/*|g" "$f"
      fi
    done
    echo "Updated prompts to use '$SRC_DIR' as source directory"
  fi

  # If goal provided, substitute in PROMPT_plan.md
  if [[ -n "$GOAL" ]] && [[ -f "PROMPT_plan.md" ]]; then
    ESCAPED_GOAL="$(escape_sed_replacement "$GOAL")"
    sed -i '' "s|\[project-specific goal\]|${ESCAPED_GOAL}|g" "PROMPT_plan.md" 2>/dev/null || \
    sed -i "s|\[project-specific goal\]|${ESCAPED_GOAL}|g" "PROMPT_plan.md"
    echo "Set project goal in PROMPT_plan.md"
  fi

  # Report
  report_results

  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "Next steps:"
  echo "  1. Edit AGENTS.md with your build/test/lint commands"
  if [[ -z "$GOAL" ]]; then
    echo "  2. Update [project-specific goal] in PROMPT_plan.md"
  fi
  echo "  3. Write specs: /ralph spec"
  echo "  4. Run planning: /ralph plan"
  echo "  5. Run building: /ralph build"
  echo ""
  echo "For autonomous (external) loop:"
  echo "  ./loop.sh plan     # Planning mode"
  echo "  ./loop.sh           # Build mode"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

# ============================================================
# PORT INIT
# ============================================================
init_port() {
  # Parse port-specific args (positional: source-lang target-lang, or --src/--tgt flags)
  local SOURCE_LANG=""
  local TARGET_LANG=""
  local positionals=()

  set -- "${REMAINING_ARGS[@]}"
  while [[ $# -gt 0 ]]; do
    case $1 in
      --src)
        if [[ -z "${2:-}" ]] || [[ "${2:-}" == -* ]]; then
          echo "Error: --src requires a language name" >&2
          exit 1
        fi
        SOURCE_LANG="$2"; shift 2
        ;;
      --tgt)
        if [[ -z "${2:-}" ]] || [[ "${2:-}" == -* ]]; then
          echo "Error: --tgt requires a language name" >&2
          exit 1
        fi
        TARGET_LANG="$2"; shift 2
        ;;
      -h|--help)
        cat << 'EOF'
Ralph Wiggum Toolkit - Port Init

USAGE:
  /ralph init --recipe port <source-lang> <target-lang>
  /ralph init --recipe port --src <source-lang> --tgt <target-lang>

EXAMPLES:
  /ralph init --recipe port dart typescript
  /ralph init --recipe port --src rust --tgt go

CREATES:
  ralph/manifest.json       Project manifest with per-file tracking
  specs/tests/              Test spec extraction output directory
  specs/src/                Source spec extraction output directory
  AGENTS.md                 Operational guide with language substitutions
  IMPLEMENTATION_PLAN.md    Task tracking (initially empty)
  PROMPT_extract_tests.md   Test extraction loop prompt
  PROMPT_extract_src.md     Source extraction loop prompt
  PROMPT_port.md            Port plan+build loop prompt
  ralph/SEMANTIC_MISMATCHES.md  Known language divergences
  ralph/PORT_STATE.md       Human-readable manifest view
  loop.sh                   External autonomous loop runner
EOF
        exit 0
        ;;
      -*)
        echo "Warning: Unknown flag '$1' ignored" >&2
        shift
        ;;
      *)
        positionals+=("$1")
        shift
        ;;
    esac
  done

  # Assign positional args
  if [[ -z "$SOURCE_LANG" ]] && [[ ${#positionals[@]} -ge 1 ]]; then
    SOURCE_LANG="${positionals[0]}"
  fi
  if [[ -z "$TARGET_LANG" ]] && [[ ${#positionals[@]} -ge 2 ]]; then
    TARGET_LANG="${positionals[1]}"
  fi

  # Normalize to lowercase
  SOURCE_LANG=$(echo "$SOURCE_LANG" | tr '[:upper:]' '[:lower:]')
  TARGET_LANG=$(echo "$TARGET_LANG" | tr '[:upper:]' '[:lower:]')

  if [[ -z "$SOURCE_LANG" ]] || [[ -z "$TARGET_LANG" ]]; then
    echo "Error: Port recipe requires source and target languages." >&2
    echo "Usage: /ralph init --recipe port <source-lang> <target-lang>" >&2
    exit 1
  fi

  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "Ralph Wiggum Toolkit: Initializing (port)"
  echo "  Source: $SOURCE_LANG → Target: $TARGET_LANG"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  echo ""
  echo "Port recipe initialization requires interactive setup"
  echo "(scanning source files, selecting roots, building manifest)."
  echo ""
  echo "The /ralph command will handle the interactive init."
  echo "This script validates the recipe and sets up the directory structure."

  # Shared setup
  init_common

  # Port-specific directories
  create_dir_if_missing "specs/tests" "Test specs directory"
  create_dir_if_missing "specs/src" "Source specs directory"

  # Copy PROMPT files from recipe templates
  create_if_missing "PROMPT_extract_tests.md" "$TEMPLATES/PROMPT_extract_tests.md" "PROMPT_extract_tests.md"
  create_if_missing "PROMPT_extract_src.md" "$TEMPLATES/PROMPT_extract_src.md" "PROMPT_extract_src.md"
  create_if_missing "PROMPT_port.md" "$TEMPLATES/PROMPT_port.md" "PROMPT_port.md"

  # Copy AGENTS.md template unchanged — ralph.md handles all placeholder substitutions
  # (it has access to all detected values: roots, test/build commands, etc.)
  create_if_missing "AGENTS.md" "$TEMPLATES/AGENTS.md" "AGENTS.md"

  # Report
  report_results

  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "Directory structure created."
  echo "The /ralph command will complete the interactive init"
  echo "(scan source files, build manifest, create PORT_STATE.md,"
  echo " substitute AGENTS.md placeholders)."
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

# ============================================================
# RETROSPECTIVE INIT
# Intentionally skips init_common — retrospective runs against
# an existing project that already has specs/, ralph/,
# IMPLEMENTATION_PLAN.md, and loop.sh.
# ============================================================
init_retrospective() {
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "Ralph Wiggum Toolkit: Initializing (retrospective)"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  # Retrospective output directory
  create_dir_if_missing "retro" "Retrospective output directory"

  # Copy PROMPT files from recipe templates
  create_if_missing "PROMPT_codegap.md" "$TEMPLATES/PROMPT_codegap.md" "PROMPT_codegap.md"
  create_if_missing "PROMPT_implgap.md" "$TEMPLATES/PROMPT_implgap.md" "PROMPT_implgap.md"
  create_if_missing "PROMPT_plugingap.md" "$TEMPLATES/PROMPT_plugingap.md" "PROMPT_plugingap.md"
  create_if_missing "PROMPT_synthesis.md" "$TEMPLATES/PROMPT_synthesis.md" "PROMPT_synthesis.md"
  create_if_missing "PROMPT_explanations.md" "$TEMPLATES/PROMPT_explanations.md" "PROMPT_explanations.md"
  create_if_missing "PROMPT_todo.md" "$TEMPLATES/PROMPT_todo.md" "PROMPT_todo.md"
  create_if_missing "AGENTS.md" "$TEMPLATES/AGENTS.md" "AGENTS.md"

  # retro_state.md populated by /ralph command (needs interactive detection)

  # Report
  report_results

  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "Directory structure created."
  echo "The /ralph retro command will complete the interactive init"
  echo "(detect source recipe, build retro_state.md, run phases)."
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

# ============================================================
# MAIN: Parse arguments and dispatch
# ============================================================

# Single-pass argument parsing: extract --recipe and build REMAINING_ARGS
RECIPE="greenfield"
REMAINING_ARGS=()

prev=""
for arg in "$@"; do
  if [[ "$prev" == "--recipe" ]]; then
    RECIPE="$arg"
    prev=""
    continue
  fi
  if [[ "$arg" == "--recipe" ]]; then
    prev="$arg"
    continue
  fi
  REMAINING_ARGS+=("$arg")
  prev=""
done

# Validate recipe
RECIPE_DIR="$RECIPES_DIR/$RECIPE"
if [[ ! -d "$RECIPE_DIR" ]]; then
  # Check user recipes
  USER_RECIPES="${HOME}/.claude/ralph-recipes/$RECIPE"
  if [[ -d "$USER_RECIPES" ]]; then
    RECIPE_DIR="$USER_RECIPES"
  else
    echo "Error: Unknown recipe '$RECIPE'." >&2
    echo "Available: $(ls "$RECIPES_DIR/" | tr '\n' ' ')" >&2
    exit 1
  fi
fi

TEMPLATES="$RECIPE_DIR/templates"

# Dispatch to recipe-specific init
case "$RECIPE" in
  greenfield)     init_greenfield ;;
  port)           init_port ;;
  retrospective)  init_retrospective ;;
  *)
    echo "Error: Recipe '$RECIPE' has no init handler." >&2
    echo "Custom recipes require manual init." >&2
    exit 1
    ;;
esac
