#!/bin/bash
# Ralph Wiggum - Initialize project for spec-driven development
# Creates the file structure Ralph needs: specs/, AGENTS.md, prompts, loop.sh

set -euo pipefail

PLUGIN_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TEMPLATES="$PLUGIN_ROOT/references/templates"

# Track what was created vs skipped
CREATED=()
SKIPPED=()

create_if_missing() {
  local target="$1"
  local source="$2"
  local description="$3"

  if [[ -f "$target" ]]; then
    SKIPPED+=("$description ($target already exists)")
  else
    cp "$source" "$target"
    CREATED+=("$description → $target")
  fi
}

create_dir_if_missing() {
  local target="$1"
  local description="$2"

  if [[ -d "$target" ]]; then
    SKIPPED+=("$description ($target already exists)")
  else
    mkdir -p "$target"
    CREATED+=("$description → $target")
  fi
}

# Escape sed replacement metacharacters for delimiter '|'
escape_sed_replacement() {
  printf '%s' "$1" | sed -e 's/[&|\\]/\\&/g'
}

# Parse arguments
SRC_DIR="src"
GOAL=""
while [[ $# -gt 0 ]]; do
  case $1 in
    --src-dir)
      if [[ -z "${2:-}" ]] || [[ "${2:-}" == -* ]]; then
        echo "Error: --src-dir requires a path argument" >&2
        exit 1
      fi
      SRC_DIR="$2"
      shift 2
      ;;
    --goal)
      if [[ -z "${2:-}" ]] || [[ "${2:-}" == -* ]]; then
        echo "Error: --goal requires a text argument" >&2
        exit 1
      fi
      GOAL="$2"
      shift 2
      ;;
    -h|--help)
      cat << 'EOF'
Ralph Wiggum Project Init

USAGE:
  /ralph-wiggum:init [OPTIONS]

OPTIONS:
  --src-dir <path>   Source code directory (default: src)
  --goal <text>      Project goal for PROMPT_plan.md placeholder
  -h, --help         Show this help

CREATES:
  specs/                  Requirement specs directory
  AGENTS.md               Operational guide (build/test commands)
  IMPLEMENTATION_PLAN.md  Task tracking (initially empty)
  PROMPT_plan.md          Planning mode prompt
  PROMPT_build.md         Build mode prompt
  loop.sh                 External autonomous loop runner
EOF
      exit 0
      ;;
    *)
      echo "Warning: Unknown argument '$1' ignored" >&2
      shift
      ;;
  esac
done

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Ralph Wiggum: Initializing project"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Create directories
create_dir_if_missing "specs" "Specs directory"

# Create files from templates
create_if_missing "AGENTS.md" "$TEMPLATES/AGENTS.md" "AGENTS.md"
create_if_missing "PROMPT_plan.md" "$TEMPLATES/PROMPT_plan.md" "PROMPT_plan.md"
create_if_missing "PROMPT_build.md" "$TEMPLATES/PROMPT_build.md" "PROMPT_build.md"

# Create empty IMPLEMENTATION_PLAN.md
if [[ ! -f "IMPLEMENTATION_PLAN.md" ]]; then
  echo "<!-- Generated by Ralph Wiggum - will be populated during planning phase -->" > IMPLEMENTATION_PLAN.md
  CREATED+=("IMPLEMENTATION_PLAN.md")
else
  SKIPPED+=("IMPLEMENTATION_PLAN.md (already exists)")
fi

# Create loop.sh
if [[ ! -f "loop.sh" ]]; then
  cp "$PLUGIN_ROOT/scripts/loop.sh" "loop.sh"
  chmod +x "loop.sh"
  CREATED+=("loop.sh (executable)")
else
  SKIPPED+=("loop.sh (already exists)")
fi

# If source dir is not "src", update prompt templates to use the right path
if [[ "$SRC_DIR" != "src" ]]; then
  ESCAPED_SRC_DIR="$(escape_sed_replacement "$SRC_DIR")"
  for f in PROMPT_plan.md PROMPT_build.md; do
    if [[ -f "$f" ]]; then
      sed -i '' "s|src/lib/\*|${ESCAPED_SRC_DIR}/lib/*|g; s|src/\*|${ESCAPED_SRC_DIR}/*|g" "$f" 2>/dev/null || \
      sed -i "s|src/lib/\*|${ESCAPED_SRC_DIR}/lib/*|g; s|src/\*|${ESCAPED_SRC_DIR}/*|g" "$f"
    fi
  done
  echo "Updated prompts to use '$SRC_DIR' as source directory"
fi

# If goal provided, substitute in PROMPT_plan.md
if [[ -n "$GOAL" ]] && [[ -f "PROMPT_plan.md" ]]; then
  ESCAPED_GOAL="$(escape_sed_replacement "$GOAL")"
  sed -i '' "s|\[project-specific goal\]|${ESCAPED_GOAL}|g" "PROMPT_plan.md" 2>/dev/null || \
  sed -i "s|\[project-specific goal\]|${ESCAPED_GOAL}|g" "PROMPT_plan.md"
  echo "Set project goal in PROMPT_plan.md"
fi

# Report
echo ""
if [[ ${#CREATED[@]} -gt 0 ]]; then
  echo "Created:"
  for item in "${CREATED[@]}"; do
    echo "  + $item"
  done
fi

if [[ ${#SKIPPED[@]} -gt 0 ]]; then
  echo ""
  echo "Skipped (already exist):"
  for item in "${SKIPPED[@]}"; do
    echo "  - $item"
  done
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Next steps:"
echo "  1. Edit AGENTS.md with your build/test/lint commands"
echo "  2. Update [project-specific goal] in PROMPT_plan.md"
echo "  3. Write specs: /ralph-wiggum:spec"
echo "  4. Run planning: /ralph-wiggum:plan"
echo "  5. Run building: /ralph-wiggum:build"
echo ""
echo "For autonomous (external) loop:"
echo "  ./loop.sh plan     # Planning mode"
echo "  ./loop.sh           # Build mode"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
